# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'seungjae oh'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-154591283-1'

menu: 
  - name: ACADEMIC PROJECTS (UCLA)
    submenu:
      - name: MATH142
        link: /math142
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/seungjo
      - name: LinkedIn
        icon: linkedin-square
        link: http://www.linkedin.com/in/seungjae-oh-095853a5
      - name: Twitter
        icon: twitter
        link: https://twitter.com/
    
